### ISSUE TITLE
Motivation and overview

### ISSUE THREAD

**Issue by ngtk** [ngtk/sail#1]
## WHY
* 継続的にアプリケーションが依存しているgemをアップデートしたい
* 既存のプロダクトとしてtachikomaがあるが、いくつか良くしたい点がある
	* 設定集中管理のため、アプリケーションエンジニアが編集しづらい
	* ドキュメントがわかりづらい

## WHAT
* 設定は集中管理ではなくアプリケーション(リポジトリ)毎で管理`sail.yml`
* アップデーターにはリポジトリだけ登録
* Kubernetesのcron jobで定時実行できるようにする
	* 可能なようにするだけで、このプロダクト自体には含めなくても良いかも

## Workflow
1. PRをつくるためのbotの設定
2. アプリケーションの設定
3. Cron jobでの定期実行
  a. bundle updateしてコミット
  b. 参考情報を含めてPRにする

### 1. PRをつくるためのbotの設定
- Personal access token (ENV)
- Commiter
  - name
  - email

config.yml
```yml
commiter:
  name: Update-Bot
  email: update-bot@update-bot.com
```

### 2. アプリケーションの設定
- GitHub repo URL
- PR
  - title
  - description
- 実行間隔・時間

sail.yml
```yml
repo_url: https://github.com/ngtk/sail
pull_request:
  title: %Y%m%d Update
frequency: daily
time: 09:00
```

### 3. Cron jobでの定期実行
- 実行間隔・時間からCron jobのmanifestファイルを自動生成
- ジョブの実行
  - リポジトリをクローン
  - bundle updateを実行
  - 設定したCommiterとしてcommit
